Charity_web/urls.py
from django.contrib import admin
from django.urls import path
from web_app import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.LandingPage.as_view(), name="landing_page"),
    path('donation/', v.AddDonation.as_view(), name="donation_page"),
    path('login/', v.Login.as_view(), name="login_page"),
    path('register/', v.Register.as_view(), name="register_page"),
    path('logout/', v.Logout.as_view(), name="logout_page"),
    path('user/', v.UserPage.as_view(), name="user_page")
]

web_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


class Type(models.TextChoices):
    foundation = "Fundacja", "Fundacja"
    non_gov_organization = "Organizacja pozarządowa", "Organizacja pozarządowa"
    local_donation = "Zbiórka lokalna", "Zbiórka lokalna"


class CategoryModel(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class InstitutionModel(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(blank=True)
    type = models.CharField(max_length=50, choices=Type.choices, default=Type.foundation)
    category = models.ManyToManyField(CategoryModel)

    def __str__(self):
        return self.name


class DonationModel(models.Model):
    quantity = models.PositiveIntegerField()
    categories = models.ManyToManyField(CategoryModel)
    institution = models.ForeignKey(InstitutionModel, on_delete=models.CASCADE)
    address = models.CharField(max_length=500)
    phone_no = models.CharField(max_length=20)
    city = models.CharField(max_length=300)
    zip_code = models.CharField(max_length=20)
    pick_up_date = models.DateField(null=False)
    pick_up_time = models.TimeField(null=False)
    pick_up_comment = models.TextField(blank=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

web_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from web_app.models import User, DonationModel


class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': "Podaj imię.. "}),
            'last_name': forms.TextInput(attrs={'placeholder': "Podaj nazwisko.."}),
            'email': forms.EmailInput(attrs={'placeholder': "e-mail.."}),

        }


class DonationForm(forms.ModelForm):
    class Meta:
        model = DonationModel
        fields = '__all__'
        widgets = {
            'categories': forms.CheckboxSelectMultiple,
            'institution': forms.RadioSelect,
            # 'pick_up_time': forms.TimeInput,
            # 'pick_up_comment': forms.TextInput,

        }

web_app/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, FormView, CreateView

from web_app.forms import CreateUserForm, DonationForm
from web_app.models import DonationModel, InstitutionModel, Type, CategoryModel, User
from django.db.models import Count, Sum
from django.core.paginator import Paginator
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin


# TODO dodawać możliwość dla funfacji więcej niż jedna kategoria
class LandingPage(View):
    def get(self, request, *args, **kwargs):
        foundation = InstitutionModel.objects.all()
        bags = DonationModel.objects.aggregate(
            total=Sum('quantity'),
            institution=Count('pk')
        ),
        context = {
            'total': bags[0]['total'],
            'institution': bags[0]['institution'],
            'foundation_id_1': foundation.filter(type=Type.foundation),
            'foundation_id_2': foundation.filter(type=Type.non_gov_organization),
            'foundation_id_3': foundation.filter(type=Type.local_donation),


        }

        return render(request, 'web_app/index.html', context)


class AddDonation(LoginRequiredMixin, FormView):
    login_url = '/login'
    form_class = DonationForm
    template_name = 'web_app/form.html'
    success_url = '/donation/'

    def get(self, request, *args, **kwargs):
        user = request.user
        institution = InstitutionModel.objects.filter(category__gt=-1)
        form = DonationForm(initial={'user': user.id})
        return render(request, 'web_app/form.html', {'form': form, 'institution': institution})

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):

        response = super().form_valid(form)
        if self.request.is_ajax():
            form.save()
            return redirect('/')
        else:
            return response


class Login(LoginView):
    template_name = 'web_app/login.html'
    redirect_authenticated_user = LandingPage

    def get(self, request, *args, **kwargs):
        form = AuthenticationForm
        return render(request, 'web_app/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return redirect('register_page')


class Logout(LogoutView):
    next_page = '/login'


class Register(View):
    def get(self, request):
        form = CreateUserForm()
        return render(request, 'web_app/register.html', {'form': form})

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
        else:
            error = "Niepowodzenie, spróbuj ponownie"
            return render(request, 'web_app/register.html', {'form': CreateUserForm, 'error': error})


class UserPage(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('/')
        else:
            user = request.user
            donation = DonationModel.objects.filter(user=user)
            bags = DonationModel.objects.filter(user=user).aggregate(
                total=Sum('quantity'))
            context = {
                'donation': donation,
                'total': bags['total']
            }
            return render(request, 'web_app/user.html', context)

templates/web_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
  </head>
  <body>
    <header>
      <nav class="container container--70">
        <ul class="nav--actions">

               {% if request.user.id == None %}
                <li><a href="{% url 'login_page' %}">Zaloguj</a></li>
          <li class="highlighted"><a href="{% url 'register_page' %}">Załóż konto</a></li>
                {% else %}
          <li class="logged-user">
              Witaj, {{ request.user.first_name }}
            <ul class="dropdown">
              <li><a href="/user/">Profil</a></li>
              <li><a href="#">Ustawienia</a></li>
                {% if request.user.is_superuser%}
                    <li><a href="/admin">Panel administratora</a></li>
                    {% endif %}
              <li><a href="{% url 'logout_page' %}">Wyloguj</a></li>
            </ul>
          </li>
            {% endif %}
        </ul>
      <br>

        <ul>
            <li><a href="/">Start</a></li>
            <li><a href="{% url 'donation_page' %}">Przekaż dary</a></li>
            <li><a href="/#steps">O co chodzi?</a></li>
            <li><a href="/#about-us">O nas</a></li>
            <li><a href="/#help">Fundacje i organizacje</a></li>
            <li><a href="/#contact">Kontakt</a></li>
        </ul>
      </nav>
      {% block content %}




    {% endblock %}

    </body>
</html>

templates/web_app/form-confirmation.html
{% extends "web_app/base.html" %}
{% load static %}
{% block content %}
      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-facebook.svg' %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-instagram.svg' %}"
          /></a>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/app.js' %}"></script>
{% endblock %}

templates/web_app/form.html
{% extends "web_app/base.html" %}
{% load static %}
{% block content %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="form-confirmation.html" method="post">
        {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
            {% for c in form.categories.field.queryset %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="radio"
                  name="categories"
                  value="{{ c.id }}"
                  id = "categories_{{ c.id }}"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >{{ c }}</span
                >
              </label>
            </div>
              {% endfor %}
           <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
                <p hidden>{{ form.user}}</p>
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" id="id_quantity"/>
              </label>
            </div>



            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
            {% for i in form.institution.field.queryset %}

            <div class="form-group form-group--checkbox">
            <p hidden id="{{ i.category.filter.0.id }}" name="category">{{ i.category.filter.0}}</p>
              <label>
                   <input type="radio"
                       name="institution"
                       value="{{ i.id }}"
                       required id="institution_{{ i.id }}"
                />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div id="institution_name_{{ i.id }}" class="title">{{ i.name }}</div>
                  <div class="subtitle">
                    {{ i.description }}
                  </div>
                </span>
              </label>
            </div>

            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" id="id_address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" id="id_city"/> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" id="id_zip_code" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" id="id_phone_no" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" id="id_pick_up_date" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" id="id_pick_up_time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5" id="id_pick_up_comment"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button onclick="myFunction()" type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span id="bags" class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span id="foundation" class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li id="street"></li>
                    <li id="city_l">Warszawa</li>
                    <li id="code">99-098</li>
                    <li id ="phone">123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li id="data">13/12/2018</li>
                    <li id ="time">15:40</li>
                    <li id="info">Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-facebook.svg' %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-instagram.svg' %}"
          /></a>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/app.js' %}">

    </script>

{% endblock %}

templates/web_app/form12.html
{% extends "web_app/base.html" %}
{% load static %}
{% block content %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="" method="POST" id="p-form">
        {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
            {% for c in form.categories.field.queryset %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="{{ c.id }}"
                  id ="categories_{{ c.id }}"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >{{ c }}</span>
              </label>
            </div>
        {% endfor %}
            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                  {{form.quantity}}
                  <li hidden>{{ form.user}}</li>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 3 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
            {% for i in form.institution.field.queryset %}
            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio"
                       name="institution"
                       value="{{i.id}}"
                       required id="institution_{{ i.id }}"
                />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">{{i}}</div>
                  <div class="subtitle">
                  {{ i.description }}
                  </div>
                </span>
              </label>
            </div>
            {% endfor %}
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica {{form.address}}</label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto {{form.city}}</label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy {{form.zip_code}}
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu {{form.phone_no}}
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data {{form.pick_up_date}} </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina {{form.pick_up_time}} </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                      {{form.pick_up_comment}}
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>

                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-facebook.svg' %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-instagram.svg' %}"
          /></a>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/app.js' %}">

    </script>


{% endblock %}

templates/web_app/user.html
{% extends "web_app/base.html" %}
{% load static %}
{% block content %}

    <div class="slogan container container--90">
        <div class="slogan--item">

                <h1>
                    Imię użytkownika: <b>{{ user.first_name }}</b><br/>
                    Nazwisko użytkownika: <b>{{ user.last_name }}</b><br/>
                    e-mail użytkownika: <b>{{ user.email }}</b><br/>

                    przekazałeś łącznie worków: <b>{{ total }} szt.</b> Dziękujemy !
                </h1>
                <br>
                <h1>
                <u>Twoja dotychczasowa pomoc</u>
                {% for d in donation %}

                    <li>Przekazano worków: <b>{{ d.quantity }}</b><br>
                        instytucji: <b>{{ d.institution.name }}</b><br>
                        data odbioru: <b>{{ d.pick_up_date }}</b><br>

                    </li>
                {% endfor %}


            </h1>
    </header>


    </footer>

    <script src="{% static 'js/app.js' %}"></script>
{% endblock %}